# Generated by Django 5.2.7 on 2025-10-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("number", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("barcode", models.CharField(blank=True, max_length=64)),
                ("supplier_name", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
