# Generated by Django 5.2.7 on 2025-10-15 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_store_product_korona_id_productstock_product_stores"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyOrderList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_lists",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-target_date", "store__name", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("on_shelf", models.PositiveIntegerField(default=1)),
                ("weekly_needed", models.PositiveIntegerField(default=0)),
                (
                    "system_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_items",
                        to="inventory.product",
                    ),
                ),
                (
                    "order_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.weeklyorderlist",
                    ),
                ),
            ],
            options={
                "ordering": ["product__name"],
                "unique_together": {("order_list", "product")},
            },
        ),
    ]
