# Generated by Django 5.2.7 on 2025-10-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_weeklyorderlist_finalize_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyorderitem",
            name="transfer_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfer_items",
                to="inventory.store",
            ),
        ),
        migrations.AddField(
            model_name="weeklyorderitem",
            name="transfer_bottles",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weeklyorderitem",
            name="joe",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weeklyorderitem",
            name="bt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weeklyorderitem",
            name="sqw",
            field=models.PositiveIntegerField(default=0),
        ),
    ]

