# Generated by Django 5.2.7 on 2025-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_weeklyorderitem_admin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='weeklyorderlist',
            name='target_date',
            field=models.DateField(db_index=True),
        ),
    ]
