# Generated by Django 5.2.7 on 2025-10-20 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_rename_weekly_to_monthly_needed"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_sold",
                    models.PositiveIntegerField(
                        default=0, help_text="Units sold in last 30 days"
                    ),
                ),
                (
                    "days_calculated",
                    models.PositiveIntegerField(
                        default=30, help_text="Days used for calculation"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_sales",
                        to="inventory.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_sales",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "store", "-calculated_at"],
                        name="inventory_m_product_acec90_idx",
                    )
                ],
                "unique_together": {("product", "store")},
            },
        ),
    ]
